### ISSUE TITLE
Store models

### ISSUE THREAD

**Issue by staskuban** [AlexVangelov/billing-js#5]
As i understanding - biloing-js uses in-memory storage.
1) Can i implement any external storage engine?
2) Can i configure billing from external storage (load nomenculatures, get payments, charges, etc) on demand?

**Comment by AlexVangelov** [comment]
Thank you @staskuban for the interest.
Check the "promises" branch in the repository, it is targeting external stores. 
There is implementation with AWS DynamoDB and IndexedDB as concept.

*But it changes the protocol dramatically because operations are not synchronous.
Sample: https://github.com/AlexVangelov/billing-js/blob/promises/samples/node/asyncStore.js
In general you can implement your own store adapter and pass it during the initialization:
`billing.config({
  store: indexedDbStore
});`
